server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.98.179.114:3306/washer?useUnicode=true&chartEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver